---
name: CustomJoinSound
author: NhanAZ
version: 1.0.0
api: 4.0.0
main: NhanAZ\CustomJoinSound\Main
src-namespace-prefix: NhanAZ\CustomJoinSound
website: https://github.com/NhanAZ
description: You will hear "Welcome to the server!" sound when joining the server
...
